name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker CLI
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push 'latest' image for main branch
      - name: Build and push Docker image (latest)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t fleetingclarity/wordle-warden:latest .
          docker push fleetingclarity/wordle-warden:latest

      # Build and push versioned image for tags
      - name: Build and push Docker image (tagged)
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          docker build -t fleetingclarity/wordle-warden:${{ github.ref_name }} .
          docker push fleetingclarity/wordle-warden:${{ github.ref_name }}
